### ISSUE TITLE
Billing >> Timesheet Entry >> Showing a run time  error.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#201]
Refer to the image below. This error occurs every time we excess Timesheet Entry.

![image](https://cloud.githubusercontent.com/assets/13091499/9454809/41ddbc76-4b08-11e5-8579-acd4eaced11a.png)

When inspecting the error we got this one. refer to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/9454957/cf5387b0-4b09-11e5-9987-396de55c27ac.png)

**Comment by AAndharia** [comment]
@mnarewec - please review this after you apply recent release sent by Japan. This looks to be same error as idle issue and if that's resolved, this must be resolved as well...as it was fixed globally.

**Comment by mnarewec** [comment]
This did not fix. After clearing cache and restart IIS

**Comment by AAndharia** [comment]
@jmervana - what's wrong with this release?

**Comment by Talmax** [comment]
@jmervana The issue is still persist even recreating the DB using script 1.9.3 that you sent.

**Comment by AAndharia** [comment]
Are you sure -  can you please double check you are using the correct version of files & database. Sorry for this, but i really wish you to double check once.

**Comment by Talmax** [comment]
@AAndharia  i'm sorry my bad.i did run a wrong script. this issue has been resolved.

**Comment by AAndharia** [comment]
Its ok. Thanks for double checking.

**Comment by Talmax** [comment]
you are welcome

**Comment by mnarewec** [comment]
This is closed.
